import Head from 'next/head';
import About from '../components/About';
import Landing from '@/components/Landing';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Landing />
      <About />
    </>
  );
}

// 1:12
