import Head from 'next/head';
import Landing from '@/components/Landing';
import About from '../components/About';
import Experience from '@/components/Experience';
import Tech from '@/components/Tech';
import Work from '@/components/Work';
import Feedbacks from '@/components/Feedbacks';
import Contact from '@/components/Contact';

export default function Home() {
  return (
    <main className=" text-white">
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Landing />
      <About />
      <Experience />
      <Tech />
      <Work />
      <Feedbacks />
      <Contact />
    </main>
  );
}
